name: KT Lint

on: pull_request

jobs:
  lint:
    name: Lint Check ğŸ•µğŸ»â€â™‚ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ğŸ‘¨ğŸ»â€ğŸ’»
        uses: actions/checkout@v2

      - name: Lint Code Base ğŸ§ª
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MD: false
          VALIDATE_XML: true
          VALIDATE_KOTLIN: true